### ISSUE TITLE
ERROR logged during shutdown `ViewDataException: You cannot view locked streams.`

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2407] opened 2021-09-08 07:51 UTC
Whilst shutting down an active Stroom, a bunch of errors have been recorded.

I'm raising tickets for all of these.

[locked.txt](https://github.com/gchq/stroom/files/7126979/locked.txt)

```
ERROR  [2021-09-07T14:16:14.887Z] [dw-120 - POST /api/data/v1/fetch] stroom.data.store.impl.DataServiceImpl -  Error fetching data stroom.pipeline.shared.FetchDataRequest@5d5c1b0a 
stroom.data.store.impl.ViewDataException: You cannot view locked streams.
	at stroom.data.store.impl.DataFetcher.lambda$getData$2(DataFetcher.java:289)
	at stroom.security.impl.SecurityContextImpl.useAsReadResult(SecurityContextImpl.java:304)
	at stroom.data.store.impl.DataFetcher.getData(DataFetcher.java:193)
	at stroom.data.store.impl.DataServiceImpl.lambda$fetch$4(DataServiceImpl.java:267)
	at stroom.security.impl.SecurityContextImpl.secureResult(SecurityContextImpl.java:381)
	at stroom.data.store.impl.DataServiceImpl.fetch(DataServiceImpl.java:266)
	at stroom.data.store.impl.DataResourceImpl.lambda$fetch$2(DataResourceImpl.java:147)
	at event.logging.impl.DefaultEventLoggingService.loggedResult(DefaultEventLoggingService.java:120)
	at event.logging.EventLoggingService.loggedResult(EventLoggingService.java:406)
	at stroom.data.store.impl.DataResourceImpl.fetch(DataResourceImpl.java:137)
```

**Comment by stroomdev10** [comment] 2021-09-09 12:13
An addendum:  This ERROR is also logged when a User clicks on a Locked Stream in the UI.  I don't think that this is an ERROR when this happens, and shoudn't be recorded in the log.

**Comment by stroomdev66** [comment] 2021-09-13 13:12
Effectively a duplicate of gh-2405

**Closed by stroomdev66** 2021-09-13 13:12 UTC
Labels: bug
