### ISSUE TITLE
Multiple Queries Leading to  Cluster Failure 

### ISSUE THREAD

**Issue by phaynes** [gchq/stroom#634] opened 2018-02-11 23:40 UTC
Hi,

With  test configuration detailed below, when submitting multiple parallel scanning queries (say 16 queries with HostName contains * as the query) against a 8 node 5.0.3 cluster,  eventual failure is being seen.  What is observed: 
1. Queries are started and initial operation appears normal;
2. CPU load maxes out to available capacity on each of the data nodes;
3. Memory, network and disk access appear normal;
4. Scanning eventually starts to slow down;
5. Nodes crash;
6. New queries hang.

Given the observation the CPU's are maxing out, it is being surmised is that CPU resource consumption across multiple queries is unmanaged and this is causing resource starvation else where.
Assuming this is the case, the fix is too eventually upgrade to Stroom V6 and push this type of search issue into ElasticSearch.

A view on whether we are interpreting the results and conclusions would be appreciated.

Help appreciated.
Kind Regards
Philip

Search Test Configuration:

- Stroom v5.0.3 (Also done with 5.0.67) 
- 4 VM's each with 64GB  RAM and two Stroom instances within each VM.
- Stroom runs within a docker container with 16GB of RAM allocated each.
- Each node has 8 CPU core allocated and thus 4CPU's per Stroom node.
- 1 VM for the Stroom MySql database (v5.5.56-mariadb), 4 CPU's, 8GB RAM
- 1  VM for an nfs mount server, 4CPU, 8GB memory
- Test data set is approximately 25M records.

We have a 8 node Stroom test cluster running under VMWare running V5.03 &

**Comment by stroomdev10** [comment] 2018-02-12 08:59
You can control the number of threads allocated to searching activity via properties.

stroom.search.extraction.maxThreads
stroom.search.extraction.maxTreadsPerTask
stroom.search.shard.maxThreads
stroom.search.shard.maxThreadsPerTask

It is possible that the values are too high for your configuration, which BTW looks a little strange to my eyes.  Why are you running two Strooms per node?

We've not performance tested docker-ised versions of Stroom and we don't as yet recommend that configuration for production use.

**Comment by phaynes** [comment] 2018-02-12 09:09
Ok - super thanks.  We will try that.

We have been trying to test a target production like config and conscious of the overhead of VM creation, it was simpler to use a smaller number of VM's with a couple of Stroom's per node. 

The test data set sizes are tiny compared to production, so even with a non-performance optimised environment, we were not expecting any problems.

**Comment by stroomdev66** [comment] 2018-02-14 09:26
Clearly resource is finite so we can't do unlimited concurrent queries, but it is fair to expect the system to not hang or crash in this scenario. The system limits the maximum number of concurrent threads but the outcome of this ought to result in slower return of results to end users rather than a crash. When you run these tests and see a slowdown/crash could you investigate what nodes are doing with jstack and memory inspection? I'd like to know if the processes are just CPU bound and will eventually return, blocking each other causing locking, or worst of all running out of memory. If nodes are running out of memory during search then all sorts of nasty things can happen as any process can fail in an unexpected way.

I think the biggest flaw we have in the system right now is the way search uses memory to store search results. We urgently need to move search results out of heap memory to protect the JVM from out of memory errors.

**Comment by phaynes** [comment] 2018-02-25 23:29
Sorry about the slow response (build issues).  Assuming settings of { stroom.search.extraction.maxThread, stroom.search.extraction.maxThreadsPerTask, stroom.search.shard.maxThreads, stroom.search.shard.maxThreadsPerTask }

On advice above, we initially backed off threads from the default of: {4, 2,  4, 2} , to 
to the more restrained set of {1, 1, 1,1}.  

Here search completed with over 20 concurrent searches. At first blush - happy days.
However, CPU utilisation was only ~30% and we did not have a firm handle as to why. 

So we performed additional runs with setting of {2, 2, 2, 2} and {2, 1, 2, 1}. In both cases failures were observed - although CPU utilisation increased.

With each of the runs jstat was run on search nodes and none of the behaviour one would expect with this type of fault, such as rampant memory allocation or excessive GC  pauses. 

What we have seen is a rise in messages such as:
"kernel:NMI watchdog: BUG: soft lockup - CPU#3 stuck for 25s! [java:11288]"

Google says  "This 'soft lockup' can happen if the kernel is busy, working on a huge amount of objects which need to be scanned, freed or allocated respectively".

Thus rightly, or wrongly, I presume this to do with matching search processing volumes against the capacity of the underlying OS?

Kind Regards,
Philip

**Comment by stroomdev66** [comment] 2018-02-26 09:35
We are experiencing similar problems when we group result data. This appears to be caused by memory exhaustion. This didn't occur in older versions of the product so work is now underway to investigate the cause. Fixing this is high priority so hopefully we'll get a patch out soon.

**Comment by stroomdev66** [comment] 2021-04-27 13:33
Hopefully fixed in 7.0

**Closed by stroomdev66** 2021-04-27 13:33 UTC
Labels: bug, p:high
