### ISSUE TITLE
Conditional Formatting is breaking existing formats

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#4654] opened 2024-12-17 10:21 UTC
Nothing was being shown, and I can't close dialog after making changes.
No obvious related messages in the console
![image](https://github.com/user-attachments/assets/14dc6c6b-a666-4bfd-8fe2-0bbc5f993102)

**Comment by stroomdev66** [comment] 2024-12-18 13:55
Duplicate of gh-4632

**Closed by stroomdev66** 2024-12-18 13:55 UTC
Labels: bug, f:dash / query, f:ui / ux
