### ISSUE TITLE
Stepping Highlighting Issues with JSON data

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#2461] opened 2021-09-23 09:09 UTC
When stepping a JSON stream with multiple records, the yellow highlighting is inconsistently covering multiple records and/or parts of records.  Similarly, the parser input pane is showing inconsistent data.

**Comment by at055612** [comment] 2021-09-23 09:11
Duplicate of #1736 I think

**Closed** 2021-09-23 09:12 UTC
Labels: bug
