### ISSUE TITLE
Shutdown (stroom-app/bin/stop.sh) could run forever by default [potential bug]

### ISSUE THREAD

**Issue by burnalting** [gchq/stroom#193] opened 2017-04-09 07:48 UTC
When stopping the Stroom application via the 

> stroom-app/bin/stop.sh

script, it does a count **up** waiting for the tomcat instance to no longer be running.

If for some reason, the tomcat process fails to terminate, then this script will run indefinitely. Either implement a count down sequence (like stroom-proxy) or set the initial WAIT variable to an appropriate value.

**Comment by stroomdev66** [comment] 2017-04-19 07:20
It is by design that the script will wait potentially forever as there are many shutdown activities that can take a long time, e.g. closing index shards. The script doesn't know exactly what it is waiting for but will just monitor termination of Tomcat. It is recommended that you monitor the logs during shutdown to ensure all processes end end properly including the closing of index shards. If shutdown is just hanging then it would be good to know which threads are failing to terminate. If absolutely necessary you can just add `now` to the stop command which will force termination, e.g. `stop.sh now`

**Comment by stroomdev66** [comment] 2017-04-19 07:38
I actually think that the proxy script should be changed to imitate the app script. The app script gives you the best of both worlds by both waiting properly for termination and allowing forced termination after 10 seconds with `now` or a user specified number of seconds, e.g. `stop.sh 60`. Version 6.0 is moving to embedded Jetty so all of this will become irrelevant.

**Closed** 2017-04-19 10:35 UTC
Labels: invalid
