### ISSUE TITLE
using the /dashboard URL requires knowledge of the uuid 

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#377] opened 2017-08-18 11:51 UTC
either allow use of the dashboard name or expose the uuid via the UI.

There is another issue/enhancement to expose a whole bunch of attributes for DB objects, so this could go with that.

**Comment by stroomdev66** [comment] 2017-08-18 12:56
Duplicate of #183

**Closed** 2018-01-08 09:09 UTC
Labels: enhancement
