### ISSUE TITLE
Missing indication of WARN & INFO messages when stepping

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#731] opened 2018-04-17 08:38 UTC
ERROR and higher messages get an icon in the top left of the stepping screen, however INFO and WARN do not.

Please add icons for WARN and INFO to the stepping function

**Comment by stroomdev66** [comment] 2018-11-27 20:13
Duplicate of gh-566

**Closed by stroomdev66** 2018-11-27 20:13 UTC
Labels: bug
