### ISSUE TITLE
Undelete confusing messages and failure

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#1358] opened 2020-01-21 10:16 UTC
v6.0.26
Selecting Un-Delete on a deleted stream brings up the dialog "Are you sure you want to delete the selected items?", press OK and "Deleted 0 record".  Nothing is deleted, but nothing is undeleted either.

**Comment by stroomdev00** [comment] 2020-01-21 10:34
If I filter for "Status = Deleted" then it works as expected, but if I remove the Status filter entirely or comment it out then this bug occurs.

**Comment by stroomdev66** [comment] 2020-04-30 16:41
Duplicate of #1500`

**Closed by stroomdev66** 2020-04-30 16:41 UTC
Labels: bug
