### ISSUE TITLE
Schema non-compliant internal log messages being produced

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#1852] opened 2020-09-09 07:35 UTC
v6.1.10/11 STROOM-USER-EVENTS feed
Events are occasionally being generated without a BaseObjectComplexType on error conditions.
```
<EventDetail>
  <Type>View</Type>
  <Description>Viewing String</Description>
  ...
  <View>
    <Outcome>
      <Success>false</Success>
      <Description>java.lang.NullPointerException</Description>
    </Outcome>
  </View>
</EventDetail>
```

**Comment by gcdev373** [comment] 2021-02-23 12:22
Duplicate of #1742

**Closed by gcdev373** 2021-02-23 12:22 UTC
Labels: bug, duplicate
