### ISSUE TITLE
Internal Searchable Items hang off Favourites if you have them in the Explorer

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#3372] opened 2023-04-12 09:15 UTC
they should hang off System

related stack attached
[2023-04-11_Explorer.txt](https://github.com/gchq/stroom/files/11210081/2023-04-11_Explorer.txt)

**Comment by stroomdev66** [comment] 2023-05-02 13:49
Possibly fixed by gh-3383

**Comment by stroomdev10** [comment] 2023-05-09 09:28
Not fixed by https://github.com/gchq/stroom/issues/3383

**Comment by stroomdev66** [comment] 2023-06-21 13:00
Unable to reproduce

**Closed** 2023-06-21 15:10 UTC
Labels: bug, f:ui / ux
