### ISSUE TITLE
Logging in when 'preventLogin' = true, then traps the user

### ISSUE THREAD

**Issue by GCHQ-11** [gchq/stroom#919] opened 2018-11-13 09:50 UTC
MAINT002
Prevent Login
As admin turn on the 'preventLogin' flag.
Logout and then login in as another user, stroom forbids access to the UI, but it kind of traps the user. So you can't logout and then log back in as admin. Seems like it should at least provide a logout button, or completely refuse the login in the first place.

**Comment by stroomdev10** [comment] 2018-11-14 09:22
dupe of 868?

**Closed** 2018-11-14 11:13 UTC
