### ISSUE TITLE
/dashboard.jsp fails with 'inputStream' on the Logon screen

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#378] opened 2017-08-18 12:14 UTC

**Comment by stroomdev10** [comment] 2017-08-18 12:23
Tried to show internals dashboard.
http://localhost:8080/dashboard.jsp?type=Dashboard&uuid=346fa8d0-50fb-4283-845a-3f47f1938809

**Comment by stroomdev66** [comment] 2017-08-18 12:50
Duplicate of #379

**Comment by GCHQ-11** [comment] 2017-09-20 07:48
Fixed with branch #409 as duplicated by #379

**Closed** 2017-09-20 07:48 UTC
Labels: bug
