### ISSUE TITLE
Reprocessing streams results in duplicates

### ISSUE THREAD

**Issue by gcdev373** [gchq/stroom#1686] opened 2020-06-24 11:38 UTC
How to reproduce:
1. Open a feed to view the streams
2. Select a derived stream (e.g. a stream of type `Events` created using `SetupSampleData`) in the top pane
3. Click the pipeline reprocess in the top pane
4. Check the "Reprocess data" box in the dialog, press OK
5. Confirm "Are you sure?" with OK
6. Confirm summary panel with OK
7. Close Alert
8. Refresh centre pane by pressing refresh button to right of panel.
9. You will see an extra Events stream resulting from the same `Raw Events` stream.
This process can be repeated.

**Comment by stroomdev10** [comment] 2020-06-24 13:01
duplicate of #1648

**Closed** 2020-06-24 13:08 UTC
Labels: bug
