### ISSUE TITLE
Deleting a node in a parent pipeline causes PipelineStreamProcessor Exceptions in child

### ISSUE THREAD

**Issue by quadhat** [gchq/stroom#436] opened 2017-10-09 08:38 UTC
The scenario is:
* Root Pipeline with multiple filter nodes:
  * `parser`
  * `readRecordCountFilter`
  * `splitFilter`
  * `workFilter1`
  * `workFilter2`
  * `schema Filter`
  * ...
* Child Pipeline inherits from Root, adds an extra filter (`extraFilter`) between `workFilter1` and `workFilter2`
* Root Pipeline is edited to remove `workFilter2`

This leads to the Child Pipeline generating errors like:

    parser       parser - ContentHandlerProxy.open(): no underlying handler provided`

Then we can't edit the Child Pipeline structure because the UI pops up an Error:

    Attempt to link from "extraFilter" to "workFilter2" but "workFilter2" is unknown`
    ...PipeineFactoryException`

and the nodes do not appear.

**Comment by stroomdev66** [comment] 2017-10-17 11:23
Duplicate of #420

**Closed by stroomdev66** 2017-10-17 11:23 UTC
Labels: bug
