### ISSUE TITLE
Pager issues in Feed Data pane for Raw Events

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#1497] opened 2020-04-28 11:00 UTC
The "1 to xx of xx" pager for Raw events is not defaulting to 100 as expected.  Any attempt to change it results in both values of xx to increase every time, including well beyond the end of a stream.  This increasing value of xx appears to roll over even after refreshing the browser so that if it last said "1 to 6450 of 6450" despite only showing the total length of data of 7 rows, then the next time it says "1 to 6457 of 6457".  The count is only reset when restarting stroom.

**Comment by stroomdev66** [comment] 2020-05-01 12:50
Duplicate of #1492

**Closed by stroomdev66** 2020-05-01 12:50 UTC
Labels: bug
