### ISSUE TITLE
Ref data lookups fail intermittently

### ISSUE THREAD

**Issue by p-kimberley** [gchq/stroom#2897] opened 2022-06-14 11:34 UTC
# Problem
We've been having intermittent issues with ref data enrichment over the past couple of months. What happens is that many of our Raw Event to Event pipelines report warnings, such as:

1. `Lookup - Map not found in streams [stream_id]`
1. `Lookup - no effective streams found`

Previously we've been able to just reprocess these Error streams and enrichment succeeds the second time around. Today, reprocessing resulted in most cases, the same errors.

The first time I noticed this was about a month ago. It seems to happen in the morning (we're GMT+11:00).
My guess is that server task `Ref Data Off-heap Store Purge`, being scheduled to run by default every second day at midnight GMT, is a probable factor, given the config properties warn about the possibility of read/write contention if this task runs during busy periods. 

# Steps taken to resolve
1. Draining all tasks, setting `stroom.pipeline.referenceData.purgeAge` to `PT1M` and manually running the server task.
1. Restarting data processing nodes
1. Deleting the ref data LMDB store from disk, then doing a node restart

1. Set `stroom.pipeline.referenceData.lmdb.readerBlockedByWriter` to `false`

After step 4 was taken, ref data lookup warnings appeared to cease.

# Additional information
The following error was also encountered:
```
Lookup - Map not found in streams [stream ID]
> ERROR: ReferenceDataLoadTaskHandler - Error using reference loader for reference stream: <stream id>:1 pipeline: Reference Loader: Unexpected processing state Optional[LOAD_IN_PROGRESS] for reference stream: 13500873:1 pipeline: Reference Loader
```

**Comment by p-kimberley** [comment] 2022-06-16 05:56
Observation of logs shows the following message appears frequently during periods where ref data lookups fail:
```
Waited for PT5.000102398S to acquired lock for RefStreamDefinition{…name=’Reference Loader’}
```
The reported time in the message tends to vary from 2 seconds anywhere up to 15 seconds.

**Comment by at055612** [comment] 2022-06-22 16:34
Have changed stroom to purge any ref streams marked as (LOAD|PURGE)_IN_PROGRESS when it boots as there is no point in keeping data in this state.

**Comment by at055612** [comment] 2022-06-22 16:37
The problems on this issues were due to an out of date reference pipe being accidentally run resulting in lookups being performed against incorrect ref streams.

**Closed by at055612** 2022-06-22 16:37 UTC
Labels: bug

**Comment by p-kimberley** [comment] 2024-06-14 09:36
This issue still seems to be present in 7.3.

In our environment, we started seeing reference data lookup `Error` streams containing the following text:
```
Lookup – Map not found in effective streams [<feed name>:<stream id>]
```

In these messages, the feed name does not match the reported stream when locating the stream by its ID through the UI.

Stepping through the pipeline, using debug output for `stroom:lookup()`, the following is shown:
```
INFO: Checking effective stream: 53106424 feed: ‘XXX’ for presence of map ‘I_ID_TO_BASIC’ (effective time: 2024-06-13T13:36:39Z, lookup time: 2024-06-14T01:43:41.572Z)

INFO: Availability of map ‘I_ID_TO_BASIC’ is ‘NOT_PRESENT’ in stream: 53106424, feed: ‘XXX’, pipeline: ‘Reference Loader’, lookup required: false
```

The feed `XXX` also does not match the stream ID in the messages.

This all started when a new reference data stream was created (today, around midnight). The new stream wasn't unusual - it definitely contains the target map and is of similar size and structure to the ones before it.

Ref data lookup pipelines have not changed recently - so it's unclear why this started happening. The mismatch between stream ID and reported feed name is concerning and suggests the wrong feed is being selected by the ref loader.

To work around the issue, the following steps were taken:
1. Stop data processor and wait for pending tasks to complete
2. Delete the latest `Reference` stream
3. Delete all processing node ref data stores
4. Cluster restart

**Comment by at055612** [comment] 2024-08-08 20:16
The issue is caused by the effective stream cache and its intern pool of effective stream sets giving out the wrong set of streams.  It only happens in niche cases where there are two sets of streams for different feeds with equal number of streams and an identical set of effective times.  In this case the intern pool will return the wrong set.
