### ISSUE TITLE
Visually Identify pipeline elements that have Filters enabled

### ISSUE THREAD

**Issue by DS177** [gchq/stroom#3100] opened 2022-11-10 08:57 UTC
It would be useful to have a visual aid to easily identify where in a Stroom pipeline you have placed a filter.
Perhaps something like having the pipeline element border bolded/highlighted or the pipeline element fill colour being something distinctive to easily visually indicate where a filter is currently active.

**Comment by at055612** [comment] 2022-11-10 09:47
I presume you mean where an XSLT has been selected on the pipeline element?

**Comment by stroomdev66** [comment] 2022-11-10 11:18
I'm not sure I understand this issue. Do you mean highlight pipelines that have active processor filters or something about the specific elements of a pipeline?

**Comment by purerehua** [comment] 2022-11-10 19:42
I would love this too. Highlighting the steps within the pipeline that have filters in the step view would be a great addition.

What the issue is here is when you are working on translations it is often desirable to enable multiple filters on different pipeline steps. So for example, I might set a filter to find the first non-empty event on a fork and then want to filter for a particular TypeId after I've made some translation changes and I want to confirm impact. I need to remember I had previously set the non-empty filter and click through looking for the teeny weeny green filter icon in the bottom right to work out why my filter to find TypeId isn't working. Hopefully that is clear as mud..  If the pipeline step went green when you had a filter in place on it (AND the filter icon was large - very tiny, why so tiny), it would be immediately obvious why a new filter you set wasn't behaving as expected.
Likely mostly an issue for people actively developing within pipelines.

**Comment by stroomdev66** [comment] 2022-11-11 09:39
Ah ok I understand now. I always forget about the stepping filters, it's that silly small icon :) I have already made some changes for 7.2 to move that filter icon to the toolbar so it is no longer an invisible thing in the corner. It makes sens to also add a little filter icon to pipeline elements in the top panel if they have an active filter.

**Comment by at055612** [comment] 2023-06-01 10:41
This has in part been covered by the filter icon moving up with the stepping icons so all filters are available on one dialog.  However, seeing which element has a filter applied is still a requirement and that is covered by #3412, so closing this one.

**Closed by at055612** 2023-06-01 10:41 UTC
Labels: enhancement, f:ui / ux

**Comment by at055612** [comment] 2023-06-20 12:08
Fixed in >7.2-beta.32
