### ISSUE TITLE
API Keys screen , ugly looking error popup

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2268] opened 2021-05-24 13:04 UTC
typed `on:` into filter 

<img width="920" alt="Screenshot 2021-05-24 at 14 03 22" src="https://user-images.githubusercontent.com/28703366/119351902-f0723700-bc98-11eb-837a-4a0cfc45fd77.png">

**Comment by at055612** [comment] 2021-05-24 15:25
Duplicate of #2265

**Closed by at055612** 2021-05-24 15:25 UTC
Labels: bug
