### ISSUE TITLE
LMDB error on startup beta.19

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#3485] opened 2023-05-30 12:28 UTC
```
ERROR  [2023-05-30T12:03:55.898Z] [Stroom Job - ScheduledExecutor] stroom.job.impl.ScheduledTaskExecutor -  Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: UnsatisfiedLinkError: could not load FFI provider Provider
  at DelegatingRefDataOffHeapStore.<init>(DelegatingRefDataOffHeapStore.java:105)
  at DelegatingRefDataOffHeapStore.class(DelegatingRefDataOffHeapStore.java:65)
  at RefDataStoreFactory.<init>(RefDataStoreFactory.java:36)
      \_ for 1st parameter
  at RefDataStoreFactory.class(RefDataStoreFactory.java:31)
  at ReferenceDataServiceImpl.<init>(ReferenceDataServiceImpl.java:142)
      \_ for 1st parameter
  while locating ReferenceDataServiceImpl
  while locating Searchable annotated with @Element(setName=,uniqueId=409, type=MULTIBINDER, keyType=)
  at SearchableProviderImpl.<init>(SearchableProviderImpl.java:21)
      \_ for 1st parameter
  at SearchableProviderImpl.class(SearchableProviderImpl.java:21)
  while locating SearchableProviderImpl
  at SearchableSearchProvider.<init>(SearchableSearchProvider.java:72)
      \_ for 6th parameter
  while locating SearchableSearchProvider
  while locating SearchProvider annotated with @Element(setName=,uniqueId=581, type=MULTIBINDER, keyType=)
  at StoreFactoryRegistry.<init>(StoreFactoryRegistry.java:24)
      \_ for 1st parameter
  at StoreFactoryRegistry.class(StoreFactoryRegistry.java:19)
  at ResultStoreManager.<init>(ResultStoreManager.java:70)
      \_ for 4th parameter
  at ResultStoreManager.class(ResultStoreManager.java:58)
  at SearchModule$EvictExpiredElements.<init>(SearchModule.java:85)
      \_ for 1st parameter
  while locating SearchModule$EvictExpiredElements
  while locating Runnable annotated with @Element(setName=,uniqueId=533, type=MAPBINDER, keyType=ScheduledJob)

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
DelegatingRefDataOffHeapStore:     "stroom.pipeline.refdata.store.offheapstore.DelegatingRefDataOffHeapStore"
Element:                           "com.google.inject.internal.Element"
Provider:                          "jnr.ffi.provider.jffi.Provider"
RefDataStoreFactory:               "stroom.pipeline.refdata.store.RefDataStoreFactory"
ReferenceDataServiceImpl:          "stroom.pipeline.refdata.ReferenceDataServiceImpl"
ResultStoreManager:                "stroom.query.common.v2.ResultStoreManager"
ScheduledJob:                      "stroom.job.api.ScheduledJob"
SearchModule$EvictExpiredElements: "stroom.search.impl.SearchModule$EvictExpiredElements"
SearchProvider:                    "stroom.query.common.v2.SearchProvider"
Searchable:                        "stroom.searchable.api.Searchable"
SearchableProviderImpl:            "stroom.searchable.impl.SearchableProviderImpl"
SearchableSearchProvider:          "stroom.searchable.impl.SearchableSearchProvider"
StoreFactoryRegistry:              "stroom.query.common.v2.StoreFactoryRegistry"
========================
End of classname legend:
========================



ERROR  [2023-05-30T12:04:05.925Z] [Stroom Job - ScheduledExecutor] stroom.job.impl.ScheduledTaskExecutor -  Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: RuntimeException: A cache called 'Reference Data - Meta ID to Ref Store Cache' already exists
  at DelegatingRefDataOffHeapStore.<init>(DelegatingRefDataOffHeapStore.java:105)
  at DelegatingRefDataOffHeapStore.class(DelegatingRefDataOffHeapStore.java:65)
  at NodeStatusServiceUtil.<init>(NodeStatusServiceUtil.java:63)
      \_ for 3rd parameter
  at NodeStatusServiceUtil.class(NodeStatusServiceUtil.java:55)
  at NodeStatusExecutor.<init>(NodeStatusExecutor.java:38)
      \_ for 1st parameter
  at NodeModule$NodeStatus.<init>(NodeModule.java:78)
      \_ for 1st parameter
  while locating NodeModule$NodeStatus
  while locating Runnable annotated with @Element(setName=,uniqueId=285, type=MAPBINDER, keyType=ScheduledJob)

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
DelegatingRefDataOffHeapStore: "stroom.pipeline.refdata.store.offheapstore.DelegatingRefDataOffHeapStore"
Element:                       "com.google.inject.internal.Element"
NodeModule$NodeStatus:         "stroom.node.impl.NodeModule$NodeStatus"
NodeStatusExecutor:            "stroom.node.impl.NodeStatusExecutor"
NodeStatusServiceUtil:         "stroom.node.impl.NodeStatusServiceUtil"
ScheduledJob:                  "stroom.job.api.ScheduledJob"
========================
End of classname legend:
========================


```

**Comment by at055612** [comment] 2023-05-31 08:29
This would seem to be an issue with lmdbjava 0.8.3.  Rolling back to 0.8.2 made this issue go away.  Leaving open as we still need to find out why 0.8.3 doesn't work

**Comment by at055612** [comment] 2023-05-31 13:32
This would seem to be caused by an outdated version of glibc on the test host, therefore closing the issue.
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: could not load FFI provider jnr.ffi.provider.jffi.Provider
        at jnr.ffi.provider.InvalidProvider$1.loadLibrary(InvalidProvider.java:49)
        at jnr.ffi.LibraryLoader.load(LibraryLoader.java:420)
        at jnr.ffi.LibraryLoader.load(LibraryLoader.java:399)
        at org.lmdbjava.Library.<clinit>(Library.java:125)
        at org.lmdbjava.Env$Builder.open(Env.java:521)
        at org.lmdbjava.Env$Builder.open(Env.java:547)
        at lmdbjava.testbed.App.run(App.java:44)
        at lmdbjava.testbed.App.main(App.java:25)
Caused by: java.lang.UnsatisfiedLinkError: could not get native definition for type `POINTER`, original error message follows: java.lang.UnsatisfiedLinkError: Unable to execute or load jffi binary stub from `/tmp`. Set `TMPDIR` or Java property `java.io.tmpdir` to a read/write path that is not mounted "noexec".
/xxxxxxxx/xxxxxxxxx/jffi3458157951401511179.so: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /xxxxxx/xxxxxxx/jffi3458157951401511179.so)
        at com.kenai.jffi.internal.StubLoader.tempLoadError(StubLoader.java:555)
        at com.kenai.jffi.internal.StubLoader.loadFromJar(StubLoader.java:454)
        at com.kenai.jffi.internal.StubLoader.load(StubLoader.java:330)
        at com.kenai.jffi.internal.StubLoader.<clinit>(StubLoader.java:618)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at com.kenai.jffi.Init.load(Init.java:68)
        at com.kenai.jffi.Foreign$InstanceHolder.getInstanceHolder(Foreign.java:50)
        at com.kenai.jffi.Foreign$InstanceHolder.<clinit>(Foreign.java:46)
        at com.kenai.jffi.Foreign.getInstance(Foreign.java:104)
        at com.kenai.jffi.Type$Builtin.lookupTypeInfo(Type.java:242)
        at com.kenai.jffi.Type$Builtin.getTypeInfo(Type.java:237)
        at com.kenai.jffi.Type.resolveSize(Type.java:155)
        at com.kenai.jffi.Type.size(Type.java:138)
        at jnr.ffi.provider.jffi.NativeRuntime$TypeDelegate.size(NativeRuntime.java:198)
        at jnr.ffi.provider.AbstractRuntime.<init>(AbstractRuntime.java:48)
        at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:77)
        at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:49)
        at jnr.ffi.provider.jffi.NativeRuntime$SingletonHolder.<clinit>(NativeRuntime.java:73)
        at jnr.ffi.provider.jffi.NativeRuntime.getInstance(NativeRuntime.java:60)
        at jnr.ffi.provider.jffi.Provider.<init>(Provider.java:29)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
        at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
        at java.base/java.lang.Class.newInstance(Class.java:645)
        at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.getInstance(FFIProvider.java:68)
        at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.<clinit>(FFIProvider.java:57)
        at jnr.ffi.provider.FFIProvider.getSystemProvider(FFIProvider.java:35)
        at jnr.ffi.LibraryLoader.create(LibraryLoader.java:89)
        at org.lmdbjava.Library.<clinit>(Library.java:125)
        at org.lmdbjava.Env$Builder.open(Env.java:521)
        at org.lmdbjava.Env$Builder.open(Env.java:547)
        at lmdbjava.testbed.App.run(App.java:44)
        at lmdbjava.testbed.App.main(App.java:25)
```

**Closed by at055612** 2023-05-31 13:32 UTC
Labels: bug

**Comment by at055612** [comment] 2026-05-20 10:29
Regarding
```
Unable to execute or load jffi binary stub from `/tmp`. Set `TMPDIR` or Java property `java.io.tmpdir` to a read/write path that is not mounted "noexec".
```

This is because the jnr/jffi lib used by LmdbJava extracts a platform specific executable binary to /tmp which is often mounted as `noexec`.

The extraction/loading of this binary is done in the `com.kenai.jffi.internal.StubLoader` class.

The solution to this is to run Stroom with the jvm arg `-Djffi.extract.dir=/tmp_with_exec`, where `/tmp_with_exec` is a dir that is mounted with `exec`.  It makes sense for this dir to be mounted as tmpfs as the binary is ephemeral and always extracted on boot.
