### ISSUE TITLE
Text output XSLTs are not rendering correctly in the stepper

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#187] opened 2017-04-03 11:32 UTC
If you have an XSLT pipeline element that outputs text rather than XML. The text is not being displayed correctly in the stepper output pane.  Text that should be tab delimited appears something like:

```
<?xml version "1.1" encoding="UTF-8">value1<?javax.xml.transform.disable-output-escaping?><?javax.xml.transform.disable-output-escaping?>value2<?javax.xml.transform.disable-output-escaping?>...
```

**Comment by stroomdev66** [comment] 2017-04-03 15:23
Duplicate of #188

**Closed by stroomdev66** 2017-04-03 15:23 UTC
Labels: bug
